### PR TITLE
Introduce TestIdentifier (DTO for TestDescriptor)

### PR DESCRIPTION
**Pull request by marcphilipp**
This pull request introduces `TestIdentifier`, an immutable DTO that contains all the information IDEs and build tools should need. We could even make it `Serializable` in a next step, currently `TestSource` prevents this.

A `TestIdentifier` knows only about the ID of its parent and does not know about its children. The `TestPlan` can be used to query this information. `TestPlan` no longer implements `TestDescriptor` but rather manages the `TestIdentifier` tree structure.

The `TestPlan` is returned by `Launcher.discoverTests()` and passed to `TestExecutionListener` methods. I've merged `TestPlanExecutionListener` and `TestExecutionListener` and added `EngineExecutionListener`. Launcher now uses an adapter that maps from `TestDescription` to `TestIdentifier` using the `TestPlan`.

However, `EngineExecutionListener` is IMHO just an intermediate solution. I would rather remove the need for engines to call the right listener methods as discussed in #29.

### CODE REVIEW

**Comment by jlink** [comment]
Just to make sure that I understand the approach fully.

Advantages:
- We don't need to split TestDescriptor and MutableTestDescriptor any more. TestDescriptor can be mutable and used by engines directly.
- TestIdentifier can be serialized (if we make Source serializable) and used by tools directly to transmit information between test running JVM and tool JVM

Disadvantages:
- One additional layer of indirection through which every test and test container has to go.
- Clients cannot navigate a tree of descriptors directly but have to use the TestPlan instance for navigation.

Anything I forgot?

**Comment by jlink** [comment]
I don't quite understand the role of TestId. Couldn't we use the uniqueId string directly?

**Comment by marcphilipp** [comment]
Regarding `TestId`: Yes, we could use the String directly. I found it awkward that `TestPlan` has many methods that take `String` arguments and `TestDescriptor` returns `String` and `Optional<String>` for its parent.

I thought about using TestId in TestDescriptor, too. But then it would have to be moved down into junit-engine-api again.

I could live with `String` if need be.

**Comment by marcphilipp** [comment]
**More advantages:**
- No way to downcast it. :wink: 
- Hopefully more natural support for dynamic tests.

**Comment by jlink** [comment]
Could you elaborate on "more natural support for dynamic tests"?

**Comment by jlink** [comment]
About `TestId` in `TestDescriptor`: Last week there was the idea to have some kind of UniqueId builder that frees an engine of thinking about uniqueness outside of its own context. Maybe an immutable object like that:

    class UniqueId {
        public static UniqueId withEngineId(String eid) { return new UniqueId(eid); }
        private String engineId;
        private List<IdPart> parts = new ArrayList<>();
        private UniqueId(String engineId) { this.engineId = engineId }
        private UniqueId(String engineId, List<IdPart> parts) { ... }
        UniqueId addPart(char separator, String part) { ... }
        IdPart popPart() { ... }
        TestId toTestId() { ... }
        String toString() { ... }
    }

    class IdPart { 
        char separator;
        String part;
    }

This could then serve as the bridge from `TestDescriptor` to `TestId`.

**Comment by mmerdes** [comment]
already merged

**Pull request closed without merging**
