### PR TITLE
Checkstyle for Javadoc

### PR DESCRIPTION
**Pull request by marcphilipp**
This pull request is related to #67 and adds Checkstyle to the Gradle build to check the following basics for Javadoc:

- Paragraphs are separated by blank lines and prefixes with `<p>` immediately before the first word of the paragraph (`JavadocParagraph`).
- Exceptions documented using `@throws` on methods must be present on their signature (`JavadocMethod`).
- The order of "tags"/"at clauses" must be `@author`, `@param`, `@return`, `@throws`, `@exception`, `@since`, `@see` (`AtclauseOrder`).
- All "tags"/"at clauses" must have a description. (`NonEmptyAtclauseDescription`).

### CODE REVIEW

**Comment by sbrannen** [comment]
Can we please have `@since` tags immediately follow `@author` tags?

**Comment by jlink** [comment]
Does it enforce Javadoc to be present?

**Comment by marcphilipp** [comment]
@sbrannen Sure.

@jlink No, it does not.

**Comment by jlink** [comment]
Then go ahead and merge it.

**Pull request closed without merging**
