### PR TITLE
OTA improvements

### PR DESCRIPTION
**Pull request by marcphilipp**
I've fixed a few things I noticed when writing assertions using our new methods in `Assertions`.

@junit-team/junit-lambda Please review!

### CODE REVIEW

**Comment by jlink** [comment]
Looks alright to me.

**Comment by sbrannen** [comment]
@marcphilipp, aside from the one suggestion I made regarding `"<no message>"`, this PR looks fine to me.

**Comment by sbrannen** [comment]
As a side note, I just realized that I totally forgot to push an experimental branch I worked on a few weeks ago: https://github.com/junit-team/junit-lambda/commits/ota-exception-hierarchy

**Comment by marcphilipp** [comment]
I've applied your feedback: The exception message now includes the FQCN in case of a `null` message. In addition, I've added the number of failures to the message (in parentheses).

I've rebased this branch onto master and merged it.

**Pull request closed without merging**
